export const CREATE_INCOME_STREAM = "CREATE_INCOME_STREAM ";
export const CREATE_INCOME_STREAM_SUCCESS = "CREATE_INCOME_STREAM_SUCCESS";
export const CREATE_INCOME_STREAM_FAILURE = "CREATE_INCOME_STREAM_SUCCESS";

export const CREATE_INCOME_STREAM_TARGET = "CREATE_INCOME_STREAM_TARGET";
export const CREATE_INCOME_STREAM_TARGET_SUCCESS = "CREATE_INCOME_STREAM_TARGET_SUCCESS";
export const CREATE_INCOME_STREAM_TARGET_FAILURE = "CREATE_INCOME_STREAM_TARGET_FAILURE";

export const FETCH_VALUE_CENTERS = "FETCH_VALUE_CENTERS"; 
export const FETCH_VALUE_CENTERS_SUCCESS="FETCH_VALUE_CENTERS_SUCCESS";
export const FETCH_VALUE_CENTERS_FAILURE="FETCH_VALUE_CENTERS_FAILURE";


