export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const CREATE_PRODUCT_TARGET = "CREATE_PRODUCT_TARGET";
export const CREATE_PRODUCT_TARGET_SUCCESS =
  "CREATE_PRODUCT_TARGET_SUCCESS";
export const CREATE_PRODUCT_TARGET_FAILURE =
  "CREATE_PRODUCT_TARGET_FAILURE";

export const GET_FILTERED_PRODUCT = "GET_FILTERED_PRODUCT";
export const GET_FILTERED_PRODUCT_SUCCESS =
  "GET_FILTERED_PRODUCT_SUCCESS";
export const GET_FILTERED_PRODUCT_FAILURE =
  "GET_FILTERED_PRODUCT_FAILURE";

export const GET_PERIODS = "GET_PERIODS";
export const GET_PERIODS_SUCCESS = "GET_PERIODS_SUCCESS";
export const GET_PERIODS_FAILURE = "GET_PERIODS_FAILURE";

export const GET_METRIC = "GET_METRIC";
export const GET_METRIC_SUCCESS = "GET_METRIC_SUCCESS";
export const GET_METRIC_FAILURE = "GET_METRIC_FAILURE";
