export const GET_REVENUE_STREAMS = "GET_REVENUE_STREAMS";
export const GET_REVENUE_STREAMS_SUCCESS = "GET_REVENUE_STREAMS_SUCCESS";
export const GET_REVENUE_STREAMS_FAILURE = "GET_REVENUE_STREAMS_FAILURE";

export const CREATE_REVENUE_STREAMS_TARGET = "CREATE_REVENUE_STREAMS_TARGET";
export const CREATE_REVENUE_STREAMS_TARGET_SUCCESS =
  "CREATE_REVENUE_STREAMS_TARGET_SUCCESS";
export const CREATE_REVENUE_STREAMS_TARGET_FAILURE =
  "CREATE_REVENUE_STREAMS_TARGET_FAILURE";
