export const GET_VALUE_CENTERS = "GET_VALUE_CENTERS";
export const GET_VALUE_CENTERS_SUCCESS = "GET_VALUE_CENTERS_SUCCESS";
export const GET_VALUE_CENTERS_FAILURE = "GET_VALUE_CENTERS_FAILURE";

export const GET_FILTERED_VALUE_CENTER = "GET_FILTERED_VALUE_CENTER";
export const GET_FILTERED_VALUE_CENTER_SUCCESS = "GET_FILTERED_VALUE_CENTER_SUCCESS";
export const GET_FILTERED_VALUE_CENTER_FAILURE = "GET_FILTERED_VALUE_CENTER_FAILURE";
